#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=pod
Namespace=kube-system
Name=$1
CPU=$2
MEMORY=$3

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $Namespace | tail +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo Resource ${RESOURCE_TYPE}, Namespace ${Namespace}, Name ${NAME}, CPU ${CPU}, Memory ${MEMORY}
done

